#include <iostream>
#include <string>

#include <affine_invariant_features/affine_invariant_feature.hpp>
#include <affine_invariant_features/feature_parameters.hpp>
#include <affine_invariant_features/results.hpp>
#include <affine_invariant_features/target.hpp>

#include <opencv2/core.hpp>
#include <opencv2/features2d.hpp>
#include <opencv2/highgui.hpp>

int main(int argc, char *argv[]) {
  namespace aif = affine_invariant_features;

  const cv::CommandLineParser args(
      argc, argv, "{ help | | }"
                  "{ use-simple-feature | <none> | will not use affine invariant sampling }"
                  "{ @parameter-file | <none> | can be generated by generate_parameter_file }"
                  "{ @target-file | <none> | can be generated by generate_target_file }"
                  "{ @result-file | <none> | }");

  if (args.has("help")) {
    args.printMessage();
    return 0;
  }

  const bool use_simple_feature(args.has("use-simple-feature"));
  const std::string param_path(args.get< std::string >("@parameter-file"));
  const std::string target_path(args.get< std::string >("@target-file"));
  const std::string result_path(args.get< std::string >("@result-file"));
  if (!args.check()) {
    args.printErrors();
    return 1;
  }

  const cv::FileStorage param_file(param_path, cv::FileStorage::READ);
  if (!param_file.isOpened()) {
    std::cerr << "Could not open " << param_path << std::endl;
    return 1;
  }

  const cv::Ptr< const aif::FeatureParameters > params(
      aif::readFeatureParameters(param_file.root()));
  if (!params) {
    std::cerr << "Could not load a parameter set from " << param_path << std::endl;
    return 1;
  }

  const cv::FileStorage target_file(target_path, cv::FileStorage::READ);
  if (!target_file.isOpened()) {
    std::cerr << "Could not open " << target_path << std::endl;
    return 1;
  }

  aif::TargetDescription target_desc;
  target_file[target_desc.getDefaultName()] >> target_desc;
  if (target_desc.imagePath.empty()) {
    std::cerr << "Could not load an image path from " << target_path << std::endl;
    return 1;
  }

  const aif::TargetData target_data(target_desc.toData());
  if (target_data.image.empty()) {
    std::cerr << "Could not load a target image described in " << target_path << std::endl;
    return 1;
  }

  cv::Mat target_image;
  if (target_data.mask.empty()) {
    target_image = target_data.image.clone();
  } else {
    target_image = target_data.image / 4;
    target_data.image.copyTo(target_image, target_data.mask);
  }
  std::cout << "Showing the target image with mask. Press any key to continue." << std::endl;
  cv::imshow("Target", target_image);
  cv::waitKey(0);

  std::cout << "Extracting features. This may take seconds or minutes." << std::endl;
  cv::Ptr< cv::Feature2D > feature;
  if (use_simple_feature) {
    feature = params->createFeature();
  } else {
    feature = aif::AffineInvariantFeature::create(params->createFeature());
  }
  aif::Results results;
  feature->detectAndCompute(target_data.image, target_data.mask, results.keypoints,
                            results.descriptors);
  results.normType = feature->defaultNorm();

  cv::Mat result_image;
  cv::drawKeypoints(target_image, results.keypoints, result_image);
  std::cout << "Showing a result image with keypoints. Press any key to continue." << std::endl;
  cv::imshow("Resutls", result_image);
  cv::waitKey(0);

  cv::FileStorage result_file(result_path, cv::FileStorage::WRITE);
  if(!result_file.isOpened()){
    std::cerr << "Could not open or create " << result_path << std::endl;
    return 1;
  }

  result_file << params->getDefaultName() << *params;
  result_file << target_desc.getDefaultName() << target_desc;
  result_file << results.getDefaultName() << results;
  std::cout << "Wrote context and results of feature extraction to " << result_path << std::endl;

  return 0;
}
